### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by borekb** [borekb/yarn-monorepo-demo#2]
### Repo structure

- [x] Build basics of the repo #1
    - repo root with core devDependencies
    - `docs` folder as Yarn 1 + node_modules project
    - `packages` as Yarn 2 + PnP + workspaces
    - `packages/app` as a demo Next.js app
    - This tests basic workability of the monorepo in VSCode, for example, if cmd-clicking into imports go to `@types/...` inside `.yarn/cache` ZIP files etc.
- [ ] Add libs inside `packages` – one with plain utility functions, one with UI elements
    - Test things like hot reload.
    - Experience in DevTools (source maps, ZIPs, ...)
- [ ] Try unplugging all packages 
- [ ] Add `examples` – those will use `portal:` to consume libs from `packages`, and probably PnP.

### VSCode tooling

- [x] TypeScript support (cmd-clicking into dependencies etc.)
- [x] Prettier
- [ ] ESLint

### Smaller things / optimizations

 - [ ] Simplify `pnpIgnorePatterns`, see https://github.com/borekb/yarn-monorepo-demo/pull/1#pullrequestreview-622934975.
